name: Venkata Malipeddi
located_in: Newark, Delaware
current_job: Sr. Systems Engineer
education:
  [
    "Master's in Computer Science Engineering",
    "Bachelor's in Mechanical Engineering",
  ]

fields_of_interests:
  [
    "Systems Administration",
    "Data Science",
    "Machine Learning",
    "Kubernetes",
    "Scripting",
    "DevOps",
  ]
technical_background:
  [
    "Systems Architect",
    "Data Science & Machine Learning in Python",
  ]
  
currently_learning: ["Docker and Kubernetes]
2023 Goals: ["Create 20+ Projects and learn at least 5 new Technologies."]
hobbies: ["Volunteering", "Charity", "Hiking", "Camping", "Farming"]
